// Code generated by roostgen. DO NOT EDIT.

package codegen

import (
	"github.com/apache/arrow-go/v18/arrow"
	"github.com/apache/arrow-go/v18/arrow/array"
	"github.com/jayjamieson/roost"
)

var metricRoostSchema = arrow.NewSchema([]arrow.Field{
	{Name: "ts", Type: &arrow.TimestampType{Unit: arrow.Microsecond}, Nullable: false},
	{Name: "host", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "cpu", Type: arrow.PrimitiveTypes.Float64, Nullable: false},
	{Name: "value", Type: arrow.PrimitiveTypes.Float64, Nullable: true},
}, nil)

// MetricRoostAppender is the generated zero-reflection RowAppender for Metric.
type MetricRoostAppender struct{}

var _ roost.RowAppender[Metric] = MetricRoostAppender{}

func (MetricRoostAppender) Schema() *arrow.Schema { return metricRoostSchema }

func (MetricRoostAppender) Partition(v *Metric) string {
	return "region=" + roost.SanitizeSegment(v.Region)
}

func (MetricRoostAppender) Append(v *Metric, b *array.RecordBuilder) {
	b.Field(0).(*array.TimestampBuilder).Append(arrow.Timestamp(v.TS.UnixMicro()))
	b.Field(1).(*array.StringBuilder).Append(v.Host)
	b.Field(2).(*array.Float64Builder).Append(v.CPU)
	if v.Value == nil {
		b.Field(3).AppendNull()
	} else {
		b.Field(3).(*array.Float64Builder).Append(*v.Value)
	}
}
